name: osum_serializable
description: Serialize almost everything you ever need! Supports serializing MaterialColor, Color, IconData, Size, Locale, UuidValue, DateTime, Directory, File, Offset, Duration, and many more.
version: 0.0.5
homepage: https://github.com/aswinmurali-io/osum_serializable

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
    git:
      url: https://github.com/definev/json_serializable.dart.git
      ref: master
      path: json_annotation
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.17.0

flutter:
